/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sohu_opengl_NativeMethodHelper */

#ifndef _Included_com_sohu_opengl_NativeMethodHelper
#define _Included_com_sohu_opengl_NativeMethodHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sohu_opengl_NativeMethodHelper
 * Method:    surfaceCreated
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sohu_opengl_NativeMethodHelper_surfaceCreated
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_sohu_opengl_NativeMethodHelper
 * Method:    surfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_sohu_opengl_NativeMethodHelper_surfaceChanged
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_sohu_opengl_NativeMethodHelper
 * Method:    onDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sohu_opengl_NativeMethodHelper_onDrawFrame
  (JNIEnv *, jclass);

/*
 * Class:     com_sohu_opengl_NativeMethodHelper
 * Method:    ping
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_sohu_opengl_NativeMethodHelper_ping
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
