/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sohu_opengl_NativeMethodHelper */

#ifndef _Included_com_sohu_opengl_NativeMethodHelper
#define _Included_com_sohu_opengl_NativeMethodHelper
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_sohu_opengl_NativeMethodHelper
 * Method:    ping
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jstring JNICALL Java_com_sohu_opengl_NativeMethodHelper_ping
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
